-- This source was generated by the Maia Framework code generator
-- Renderer class: class org.maiaframework.gen.renderers.CreateTableSqlRenderer


CREATE TABLE maia.all_field_types (
    created_by_id uuid NOT NULL REFERENCES maia.party(id),
    created_by_name text NOT NULL,
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    last_modified_by_id uuid NOT NULL REFERENCES maia.party(id),
    last_modified_by_name text NOT NULL,
    last_modified_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_boolean boolean NOT NULL,
    some_boolean_nullable boolean NULL,
    some_boolean_type boolean NOT NULL,
    some_boolean_type_nullable boolean NULL,
    some_boolean_type_provided boolean NOT NULL,
    some_boolean_type_provided_nullable boolean NULL,
    some_dto jsonb NOT NULL,
    some_dto_nullable jsonb NULL,
    some_enum text NOT NULL,
    some_enum_nullable text NULL,
    some_instant timestamp(3) with time zone NOT NULL,
    some_instant_modifiable timestamp(3) with time zone NOT NULL,
    some_instant_modifiable_nullable timestamp(3) with time zone NULL,
    some_instant_nullable timestamp(3) with time zone NULL,
    some_int integer NOT NULL,
    some_int_modifiable integer NOT NULL,
    some_int_nullable integer NULL,
    some_int_type integer NOT NULL,
    some_int_type_nullable integer NULL,
    some_int_type_provided integer NOT NULL,
    some_int_type_provided_nullable integer NULL,
    some_list_of_enums text[] NOT NULL,
    some_list_of_instants timestamp(3) with time zone[] NOT NULL,
    some_list_of_local_dates date[] NOT NULL,
    some_list_of_periods text[] NOT NULL,
    some_list_of_string_types text[] NOT NULL,
    some_list_of_strings text[] NOT NULL,
    some_local_date_modifiable date NOT NULL,
    some_long_type bigint NOT NULL,
    some_long_type_nullable bigint NULL,
    some_long_type_provided bigint NOT NULL,
    some_long_type_provided_nullable bigint NULL,
    some_map_of_string_to_integer jsonb NOT NULL,
    some_map_of_string_type_to_string_type jsonb NOT NULL,
    some_period_modifiable text NOT NULL,
    some_period_nullable text NULL,
    some_provided_string_type text NOT NULL,
    some_provided_string_type_nullable text NULL,
    some_string text NOT NULL,
    some_string_modifiable text NOT NULL,
    some_string_nullable text NULL,
    some_string_type text NOT NULL,
    some_string_type_nullable text NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX all_field_types_some_int_type_uidx ON maia.all_field_types(some_int_type);
CREATE UNIQUE INDEX all_field_types_some_long_type_uidx ON maia.all_field_types(some_long_type);
CREATE UNIQUE INDEX all_field_types_some_string_uidx ON maia.all_field_types(some_string);
CREATE UNIQUE INDEX all_field_types_some_string_nullable_uidx ON maia.all_field_types(some_string_nullable);
CREATE UNIQUE INDEX all_field_types_some_string_type_uidx ON maia.all_field_types(some_string_type);
CREATE INDEX all_field_types_some_boolean_some_string_modifiable_idx ON maia.all_field_types(some_boolean, some_string_modifiable);


CREATE TABLE maia.simple (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX simple_some_string_uidx ON maia.simple(some_string);


CREATE TABLE maia.effective_timestamp (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    effective_from timestamp(3) with time zone NULL,
    effective_to timestamp(3) with time zone NULL,
    id uuid NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX effective_timestamp_some_string_idx ON maia.effective_timestamp(some_string);
