-- This source was generated by the Maia Framework code generator
-- Renderer class: class org.maiaframework.gen.renderers.CreateTableSqlRenderer


CREATE TABLE testing.nullable_fields (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_boolean boolean NULL,
    some_boolean_type boolean NULL,
    some_enum text NULL,
    some_instant timestamp(3) with time zone NULL,
    some_int integer NULL,
    some_int_type integer NULL,
    some_local_date date NULL,
    some_long_type bigint NULL,
    some_period text NULL,
    some_provided_boolean_type boolean NULL,
    some_provided_int_type integer NULL,
    some_provided_long_type bigint NULL,
    some_provided_string_type text NULL,
    some_string text NULL,
    some_string_type text NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX nullable_fields_some_string_uidx ON testing.nullable_fields(some_string);


CREATE TABLE testing.effective_timestamp (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    effective_from timestamp(3) with time zone NULL,
    effective_to timestamp(3) with time zone NULL,
    id uuid NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX effective_timestamp_some_string_idx ON testing.effective_timestamp(some_string);


CREATE TABLE testing.simple (
    created_by_id uuid NOT NULL REFERENCES testing.party(id),
    created_by_name text NOT NULL,
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    last_modified_by_id uuid NOT NULL REFERENCES testing.party(id),
    last_modified_by_name text NOT NULL,
    last_modified_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_boolean boolean NOT NULL,
    some_boolean_nullable boolean NULL,
    some_boolean_type boolean NOT NULL,
    some_boolean_type_nullable boolean NULL,
    some_boolean_type_provided boolean NOT NULL,
    some_boolean_type_provided_nullable boolean NULL,
    some_dto jsonb NOT NULL,
    some_dto_nullable jsonb NULL,
    some_enum text NOT NULL,
    some_enum_nullable text NULL,
    some_instant timestamp(3) with time zone NOT NULL,
    some_instant_modifiable timestamp(3) with time zone NOT NULL,
    some_instant_modifiable_nullable timestamp(3) with time zone NULL,
    some_instant_nullable timestamp(3) with time zone NULL,
    some_int integer NOT NULL,
    some_int_modifiable integer NOT NULL,
    some_int_nullable integer NULL,
    some_int_type integer NOT NULL,
    some_int_type_nullable integer NULL,
    some_int_type_provided integer NOT NULL,
    some_int_type_provided_nullable integer NULL,
    some_list_of_enums text[] NOT NULL,
    some_list_of_instants timestamp(3) with time zone[] NOT NULL,
    some_list_of_local_dates date[] NOT NULL,
    some_list_of_periods text[] NOT NULL,
    some_list_of_string_types text[] NOT NULL,
    some_list_of_strings text[] NOT NULL,
    some_local_date_modifiable date NOT NULL,
    some_long_type bigint NOT NULL,
    some_long_type_nullable bigint NULL,
    some_long_type_provided bigint NOT NULL,
    some_long_type_provided_nullable bigint NULL,
    some_map_of_string_to_integer jsonb NOT NULL,
    some_map_of_string_type_to_string_type jsonb NOT NULL,
    some_period_modifiable text NOT NULL,
    some_period_nullable text NULL,
    some_provided_string_type text NOT NULL,
    some_provided_string_type_nullable text NULL,
    some_string text NOT NULL,
    some_string_modifiable text NOT NULL,
    some_string_nullable text NULL,
    some_string_type text NOT NULL,
    some_string_type_nullable text NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX simple_some_int_type_uidx ON testing.simple(some_int_type);
CREATE UNIQUE INDEX simple_some_long_type_uidx ON testing.simple(some_long_type);
CREATE UNIQUE INDEX simple_some_string_uidx ON testing.simple(some_string);
CREATE UNIQUE INDEX simple_some_string_nullable_uidx ON testing.simple(some_string_nullable);
CREATE UNIQUE INDEX simple_some_string_type_uidx ON testing.simple(some_string_type);
CREATE INDEX simple_some_boolean_some_string_modifiable_idx ON testing.simple(some_boolean, some_string_modifiable);


CREATE TABLE testing.ttl (
    created_at timestamp(3) with time zone NOT NULL,
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX ttl_created_timestamp_utc_idx ON testing.ttl(created_timestamp_utc);


CREATE TABLE testing.history_sample (
    created_by_id uuid NOT NULL REFERENCES testing.party(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    last_modified_by_id uuid NOT NULL REFERENCES testing.party(id),
    last_modified_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX history_sample_some_string_uidx ON testing.history_sample(some_string);


CREATE TABLE testing.history_sample_history (
    change_type text NOT NULL,
    created_by_id uuid NOT NULL REFERENCES testing.party(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    last_modified_by_id uuid NOT NULL REFERENCES testing.party(id),
    last_modified_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(id, version)
);
CREATE INDEX hist_history_sample_some_string_uidx ON testing.history_sample_history(some_string);


CREATE TABLE testing.super (
    type_discriminator text not null,
    created_by_id uuid NOT NULL REFERENCES testing.party(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    last_modified_by_id uuid NOT NULL REFERENCES testing.party(id),
    last_modified_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_int integer NULL,
    some_string text NULL,
    some_unique_string text NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX sub_two_some_unique_string_uidx ON testing.super(some_unique_string, type_discriminator);


CREATE TABLE testing.history_super (
    type_discriminator text not null,
    created_by_id uuid NOT NULL REFERENCES testing.party(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    last_modified_by_id uuid NOT NULL REFERENCES testing.party(id),
    last_modified_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_int integer NULL,
    some_string text NULL,
    version bigint NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.history_super_history (
    type_discriminator text not null,
    change_type text NOT NULL,
    created_by_id uuid NOT NULL REFERENCES testing.party(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    last_modified_by_id uuid NOT NULL REFERENCES testing.party(id),
    last_modified_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_int integer NULL,
    some_string text NULL,
    version bigint NOT NULL,
    PRIMARY KEY(id, version)
);


CREATE TABLE testing.some_versioned (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX some_versioned_some_int_uidx ON testing.some_versioned(some_int);


CREATE TABLE testing.with_optional_index_field (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_optional_string1 text NULL,
    some_optional_string2 text NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);
CREATE INDEX with_optional_index_field_some_optional_string1_idx ON testing.with_optional_index_field(some_optional_string1);
CREATE INDEX with_optional_index_field_some_optional_string2_some_string_idx ON testing.with_optional_index_field(some_optional_string2, some_string);


CREATE TABLE testing.very_simple (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.foreign_key_parent (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.foreign_key_child (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    parent_id uuid NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.alpha (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.bravo (
    alpha_id uuid NOT NULL REFERENCES testing.alpha(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.charlie (
    bravo_id uuid NOT NULL REFERENCES testing.bravo(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.alpha_ag_grid (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.bravo_ag_grid (
    alpha_id uuid NOT NULL REFERENCES testing.alpha_ag_grid(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.charlie_ag_grid (
    bravo_id uuid NOT NULL REFERENCES testing.bravo_ag_grid(id),
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.left (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.right (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_int integer NOT NULL,
    some_string text NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.many_to_many_join (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    last_modified_timestamp_utc timestamp(3) with time zone NOT NULL,
    left_id uuid NOT NULL REFERENCES testing.left(id),
    right_id uuid NOT NULL REFERENCES testing.right(id),
    PRIMARY KEY(id)
);


CREATE TABLE testing.unmodifiable (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id uuid NOT NULL,
    some_unique_int integer NOT NULL,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX unmodifiable_some_unique_int_uidx ON testing.unmodifiable(some_unique_int);


CREATE TABLE testing.composite_primary_key (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_int integer NOT NULL,
    some_modifiable_string text NOT NULL,
    some_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(some_int, some_string)
);


CREATE TABLE testing.composite_primary_key_history (
    change_type text NOT NULL,
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_int integer NOT NULL,
    some_modifiable_string text NOT NULL,
    some_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(some_int, some_string, version)
);


CREATE TABLE testing.non_surrogate_primary_key (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_modifiable_string text NOT NULL,
    some_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(some_string)
);


CREATE TABLE testing.non_surrogate_primary_key_history (
    change_type text NOT NULL,
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    some_modifiable_string text NOT NULL,
    some_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(some_string, version)
);


CREATE TABLE testing.non_surrogate_id_primary_key (
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id text NOT NULL,
    some_modifiable_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE testing.non_surrogate_id_primary_key_history (
    change_type text NOT NULL,
    created_timestamp_utc timestamp(3) with time zone NOT NULL,
    id text NOT NULL,
    some_modifiable_string text NOT NULL,
    version bigint NOT NULL,
    PRIMARY KEY(id, version)
);
