
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.flyway: DEBUG

maia:
  jobs:
    api:
      base-path: /api
  problems:
    type_prefix: "showcase_"


server:
  port: 3200


spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/maia_db"
    password: maia_app_password
    username: maia_app
  elasticsearch:
    uris: [ 'http://localhost:9200' ]
    username: elastic
    password: maia_elastic_password
  flyway:
    user: maia_owner
    password: maia_owner_password
    default-schema: maia
  mvc:
    problemdetails:
      enabled: true
  ssl:
    bundle:
      pem:
        elasticsearch-client:
          truststore:
            certificate: "classpath:certs/local-elasticsearch-ca.crt"
  web:
    resources:
      static-locations: classpath:/static/browser
