package org.maiaframework.webapp.domain


object ErrorCodes {

    val DUPLICATE_KEY_EXCEPTION = ErrorCode("DUPLICATION_KEY_EXCEPTION")

    val INVALID_REQUEST_PARAMETER = ErrorCode("INVALID_REQUEST_PARAMETER")

    val UNEXPECTED_INTERNAL_SERVER_ERROR = ErrorCode("UNEXPECTED_INTERNAL_SERVER_ERROR")

    val VALIDATION_ERROR = ErrorCode("VALIDATION_ERROR")

    val FOREIGN_KEY_VIOLATION = ErrorCode("FOREIGN_KEY_VIOLATION")

}
